package com.etermax.spacehorse.core.inapps.repository;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.etermax.spacehorse.core.common.repository.dynamo.AbstractDynamoDAO;
import com.etermax.spacehorse.core.inapps.domain.market.ios.IosReceipt;

@DynamoDBTable(tableName = "ios_purchase")
public class IosPurchaseReceipt implements AbstractDynamoDAO {

	public static final String USER_INDEX_NAME = "iosPurchaseIndexbyUserId";

	@DynamoDBHashKey(attributeName = "transactionId")
	private String transactionId;

	@DynamoDBIndexHashKey(attributeName = "userId", globalSecondaryIndexName = USER_INDEX_NAME)
	private String userId;

	@DynamoDBAttribute(attributeName = "productId")
	private String productId;

	@DynamoDBAttribute(attributeName = "data")
	private String data;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private Date createdDate;

	public IosPurchaseReceipt() {
	}

	public IosPurchaseReceipt(IosReceipt receipt, String userId) {
		this.transactionId = receipt.getTransactionId();
		this.productId = receipt.getProductId();
		this.data = receipt.getData();
		this.userId = userId;
	}

	public IosPurchaseReceipt(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Override
	public void setId(String id) {
		this.transactionId = id;
	}

	@Override
	public String getId() {
		return this.transactionId;
	}
}
