package com.etermax.spacehorse.core.battle.repository.dynamo;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.etermax.spacehorse.core.battle.model.PlayerWinRate;
import com.etermax.spacehorse.core.common.repository.dynamo.AbstractDynamoDAO;

@DynamoDBTable(tableName = "playerWinRate")
public class DynamoPlayerWinRate implements AbstractDynamoDAO {

	@DynamoDBHashKey(attributeName = "userId")
	private String userId;

	@DynamoDBAttribute(attributeName = "win")
	private int win = 0;

	@DynamoDBAttribute(attributeName = "lose")
	private int lose = 0;

	@DynamoDBAttribute(attributeName = "tie")
	private int tie = 0;

	@DynamoDBAttribute(attributeName = "mmr")
	private int mmr = 0;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private Date createdDate;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private Date lastUpdatedDate;

	public DynamoPlayerWinRate() {
	}

	public DynamoPlayerWinRate(String userId) {
		this.setUserId(userId);
	}

	public static DynamoPlayerWinRate fromPlayerWinRate(PlayerWinRate playerWinRate) {
		DynamoPlayerWinRate dynamoPlayerWinRate = new DynamoPlayerWinRate(playerWinRate.getUserId());
		dynamoPlayerWinRate.setLose(playerWinRate.getLose());
		dynamoPlayerWinRate.setTie(playerWinRate.getTie());
		dynamoPlayerWinRate.setWin(playerWinRate.getWin());
		dynamoPlayerWinRate.setMmr(playerWinRate.getMmr());
		return dynamoPlayerWinRate;
	}

	public static PlayerWinRate mapToPlayerWinRate(DynamoPlayerWinRate dynamoPlayerWinRate) {
		return new PlayerWinRate(//
				dynamoPlayerWinRate.getUserId(),//
				dynamoPlayerWinRate.getWin(), //
				dynamoPlayerWinRate.getLose(),//
				dynamoPlayerWinRate.getTie(), //
				dynamoPlayerWinRate.getMmr());
	}

    @Override
    public void setId(String id) {
        this.setUserId(id);
    }

    @Override
    public String getId() {
        return getUserId();
    }

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getWin() {
		return win;
	}

	public void setWin(int win) {
		this.win = win;
	}

	public int getLose() {
		return lose;
	}

	public void setLose(int lose) {
		this.lose = lose;
	}

	public int getTie() {
		return tie;
	}

	public void setTie(int tie) {
		this.tie = tie;
	}

	public int getMmr() {
		return mmr;
	}

	public void setMmr(int mmr) {
		this.mmr = mmr;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

}
